export const OPEN_DESKTOP_MENU = "OPEN_DESKTOP_MENU";
export const CLOSE_DESKTOP_MENU = "CLOSE_DESKTOP_MENU";
export const SHOW_MENU_CONTENT = "SHOW_MENU_CONTENT";
export const HIDE_MENU_CONTENT = "HIDE_MENU_CONTENT";
